version: '3'

services:
  app:
    container_name: umar_team_app
    image: aiappliedsciences.azurecr.io/team_app:latest
    restart: always
    env_file: ./../demoApp/.env_azure
    ports:
      - "15080:15080"
    networks:
      - umar_team_app_network
    command: ["python3", "main.py"]

networks:
  umar_team_app_network:
    driver: bridge
    name: umar_team_app_network
